import{useMemo,useState}from"react";import{BookOpen,Check,CheckCircle2,ChevronLeft,ChevronRight,FileText,Home,Mic,Plus,Search,Settings,Sparkles,Sun,Trash2,X}from"lucide-react";
type Tab="home"|"notes"|"journal"|"tasks"|"search"|"settings";
type Note={id:number,title:string,body:string,tag:string};type Entry={id:number,date:string,title:string,body:string,mood?:string};type Task={id:number,title:string,done:boolean,priority:"low"|"medium"|"high"};
const themes={Cloud:{bg:"#f7f3f8",accent:"#8f80f7"},Lavender:{bg:"#f1ecfb",accent:"#8570dc"},Peach:{bg:"#fff1eb",accent:"#f39b78"},Sage:{bg:"#eef6ef",accent:"#79a982"},Sky:{bg:"#edf5ff",accent:"#72a6df"},Butter:{bg:"#fffaf0",accent:"#e2b954"},Midnight:{bg:"#1f1d25",accent:"#a99bff"}};
const seedNotes:Note[]=[{id:1,title:"Content Ideas",body:"Faceless content ideas for the next batch...",tag:"Ideas"},{id:2,title:"Japan Plan",body:"Colleges, visas, language and travel notes.",tag:"Personal"},{id:3,title:"Editing Workflow",body:"Tools, shortcuts, process...",tag:"Work"}];
const seedEntries:Entry[]=[{id:1,date:"Sep 18, 2026",title:"A Calm Beginning",body:"Today felt different. I realized that maybe I don't need everything figured out. I just need to keep showing up.",mood:"Calm"}];
function App(){const[tab,setTab]=useState<Tab>("home");const[theme,setTheme]=useState<keyof typeof themes>("Cloud");const[notes,setNotes]=useState(seedNotes);const[entries,setEntries]=useState(seedEntries);const[tasks,setTasks]=useState<Task[]>([{id:1,title:"Practice English",done:false,priority:"high"},{id:2,title:"Work on project",done:false,priority:"medium"},{id:3,title:"Send outreach",done:false,priority:"medium"},{id:4,title:"Workout",done:false,priority:"low"}]);const[capture,setCapture]=useState("");const[inbox,setInbox]=useState<string[]>([]);const[selectedNote,setSelectedNote]=useState<Note|null>(null);const[selectedEntry,setSelectedEntry]=useState<Entry|null>(null);const[query,setQuery]=useState("");
const completed=tasks.filter(t=>t.done).length;const current=themes[theme];
const addTask=(title:string)=>{if(!title.trim())return;setTasks(v=>[...v,{id:Date.now(),title:title.trim(),done:false,priority:"medium"}])};
const addNote=()=>{const n={id:Date.now(),title:"Untitled note",body:"",tag:"Personal"};setNotes(v=>[n,...v]);setSelectedNote(n);setTab("notes")};
const addEntry=()=>{const e={id:Date.now(),date:new Date().toLocaleDateString("en-US",{month:"short",day:"2-digit",year:"numeric"}),title:"",body:"",mood:""};setEntries(v=>[e,...v]);setSelectedEntry(e);setTab("journal")};
const filtered=[...notes.map(n=>({kind:"Note",title:n.title,body:n.body,id:n.id})),...entries.map(e=>({kind:"Journal",title:e.title||"Untitled entry",body:e.body,id:e.id})),...tasks.map(t=>({kind:"Task",title:t.title,body:t.done?"Completed":"Open",id:t.id}))].filter(x=>(x.title+" "+x.body).toLowerCase().includes(query.toLowerCase()));
return <div className="morrow-shell" style={{background:current.bg}}><div className="app-frame">
<Header tab={tab} setTab={setTab}/>
{tab==="home"&&<Home tasks={tasks} completed={completed} setTab={setTab} setCapture={setCapture} capture={capture} setInbox={setInbox} inbox={inbox} onAddTask={addTask} onAddEntry={addEntry}/>}
{tab==="notes"&&<Notes notes={notes} selected={selectedNote} setSelected={setSelectedNote} onAdd={addNote} onSave={(n)=>setNotes(v=>v.map(x=>x.id===n.id?n:x))}/>}
{tab==="journal"&&<Journal entries={entries} selected={selectedEntry} setSelected={setSelectedEntry} onAdd={addEntry} onSave={(e)=>setEntries(v=>v.map(x=>x.id===e.id?e:x))}/>}
{tab==="tasks"&&<Tasks tasks={tasks} setTasks={setTasks} onAdd={addTask}/>}
{tab==="search"&&<SearchView query={query} setQuery={setQuery} results={filtered}/>}
{tab==="settings"&&<SettingsView theme={theme} setTheme={setTheme}/>}
</div><Nav tab={tab} setTab={setTab} onAdd={()=>setCapture("open")}/>
{capture==="open"&&<QuickCapture value="" onClose={()=>setCapture("")} onSave={(text)=>{setInbox(v=>[text,...v]);setCapture("")}}/>}</div>}
function Header({tab,setTab}:{tab:Tab;setTab:(t:Tab)=>void}){return <div className="flex items-center justify-between mb-7"><div><div className="text-xs tracking-[.28em] uppercase font-semibold" style={{color:"#8a78e7"}}>Morrow</div>{tab==="home"&&<div className="serif text-4xl mt-2">Good morning</div>}</div><div className="flex gap-2">{tab!=="home"&&<button className="p-2 rounded-full bg-white/70 border" onClick={()=>setTab("home")}><ChevronLeft size={19}/></button>}<button className="p-2 rounded-full bg-white/70 border" onClick={()=>setTab("settings")}><Settings size={19}/></button></div></div>}
function Home({tasks,setTab,setCapture,capture,setInbox,inbox,onAddTask,onAddEntry}:{tasks:Task[];completed:number;setTab:(t:Tab)=>void;setCapture:(v:string)=>void;capture:string;setInbox:(v:string[])=>void;inbox:string[];onAddTask:(v:string)=>void;onAddEntry:()=>void}){const[t,setT]=useState("");return <main>
<div className="mb-5"><div className="text-sm text-muted-foreground">Tuesday, September 22</div><div className="text-base mt-2 text-[#6f6677]">A small place for your thoughts, plans and a better tomorrow.</div></div>
<button onClick={()=>setCapture("open")} className="soft w-full rounded-3xl p-5 text-left pastel-lavender mb-7 flex items-center justify-between"><div><div className="text-lg font-semibold">Quick capture</div><div className="text-sm opacity-70 mt-1">What's on your mind?</div></div><div className="h-11 w-11 rounded-full bg-white flex items-center justify-center shadow-sm"><Plus/></div></button>
<section className="mb-7"><div className="flex items-center justify-between mb-3"><h2 className="serif text-2xl">Today's tasks</h2><button className="text-sm underline" onClick={()=>setTab("tasks")}>See all</button></div><div className="soft rounded-3xl overflow-hidden">{tasks.slice(0,5).map(task=><button key={task.id} className="w-full flex items-center gap-3 px-4 py-4 border-b last:border-0 text-left" onClick={()=>setTab("tasks")}><span className={task.done?"h-5 w-5 rounded-full bg-[#b7aaf7] flex items-center justify-center text-white":"h-5 w-5 rounded-full border-2 border-[#b6acc1]"}>{task.done&&<Check size={12}/>}</span><span className={task.done?"line-through opacity-50":"font-medium"}>{task.title}</span><span className="ml-auto text-xs px-2 py-1 rounded-full bg-white/70">{task.priority}</span></button>)}</div><div className="mt-3 flex gap-2"><input value={t} onChange={e=>setT(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){onAddTask(t);setT("")}}} placeholder="Add a task..." className="flex-1 soft rounded-2xl px-4 py-3 outline-none"/><button onClick={()=>{onAddTask(t);setT("")}} className="h-12 w-12 rounded-2xl bg-[#28252d] text-white flex items-center justify-center"><Plus size={19}/></button></div></section>
<section className="mb-7"><div className="flex items-center justify-between mb-3"><h2 className="serif text-2xl">Continue writing</h2><button className="text-sm underline" onClick={()=>setTab("journal")}>See all</button></div><button onClick={onAddEntry} className="soft rounded-3xl p-5 w-full text-left pastel-peach"><div className="text-xs opacity-60">September 18, 2026 · Calm</div><div className="text-xl font-semibold mt-2">A Calm Beginning</div><div className="text-sm opacity-70 mt-2 line-clamp-3">Today felt different. I realized that maybe I don't need everything figured out...</div></button></section>
<section><div className="flex items-center justify-between mb-3"><h2 className="serif text-2xl">Recent notes</h2><button className="text-sm underline" onClick={()=>setTab("notes")}>See all</button></div><div className="grid grid-cols-2 gap-3">{["Content Ideas","Japan Plan","Editing Workflow","Random Thoughts"].map((x,i)=><button key={x} onClick={()=>setTab("notes")} className={`soft rounded-3xl p-4 text-left ${i%2===0?"pastel-blue":"pastel-sage"}`}><FileText size={17}/><div className="font-medium mt-6">{x}</div><div className="text-xs opacity-60 mt-1">Updated recently</div></button>)}</div></section>
</main>}
function Notes({notes,selected,setSelected,onAdd,onSave}:{notes:Note[];selected:Note|null;setSelected:(n:Note|null)=>void;onAdd:()=>void;onSave:(n:Note)=>void}){const[query,setQuery]=useState("");if(selected)return <NoteEditor note={selected} onBack={()=>setSelected(null)} onSave={onSave}/>;const shown=notes.filter(n=>(n.title+" "+n.body).toLowerCase().includes(query.toLowerCase()));return <main><div className="flex items-end justify-between mb-5"><div><div className="text-xs tracking-[.22em] uppercase opacity-50">Notes</div><h1 className="serif text-4xl mt-1">Your ideas</h1></div><button onClick={onAdd} className="h-12 w-12 rounded-2xl bg-[#8d7df0] text-white flex items-center justify-center"><Plus/></button></div><div className="soft rounded-2xl px-4 py-3 flex items-center gap-2 mb-5"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} className="bg-transparent outline-none flex-1" placeholder="Search your notes..."/></div><div className="grid gap-3">{shown.map(n=><button onClick={()=>setSelected(n)} key={n.id} className="soft rounded-3xl p-5 text-left hover:-translate-y-0.5 transition"><div className="text-xs uppercase tracking-[.16em] opacity-50">{n.tag}</div><div className="font-semibold text-lg mt-2">{n.title}</div><div className="text-sm opacity-65 mt-1">{n.body}</div></button>)}</div></main>}
function NoteEditor({note,onBack,onSave}:{note:Note;onBack:()=>void;onSave:(n:Note)=>void}){const[local,setLocal]=useState(note);return <main><div className="flex items-center justify-between mb-4"><button onClick={onBack}><ChevronLeft/></button><button onClick={()=>onSave(local)} className="px-4 py-2 rounded-2xl bg-[#28252d] text-white">Save</button></div><input value={local.title} onChange={e=>setLocal({...local,title:e.target.value})} placeholder="Title" className="w-full bg-transparent outline-none serif text-4xl mb-4"/><textarea value={local.body} onChange={e=>setLocal({...local,body:e.target.value})} placeholder="Write anything..." className="w-full min-h-[55vh] bg-transparent outline-none resize-none leading-8 text-lg"/><div className="soft rounded-2xl p-3 mt-3 flex gap-4 text-[#7568d7]"><Mic/><span className="text-sm">Voice capture ready for later AI transcription</span></div></main>}
function Journal({entries,selected,setSelected,onAdd,onSave}:{entries:Entry[];selected:Entry|null;setSelected:(e:Entry|null)=>void;onAdd:()=>void;onSave:(e:Entry)=>void}){if(selected)return <JournalEditor entry={selected} onBack={()=>setSelected(null)} onSave={onSave}/>;return <main><div className="flex items-end justify-between mb-5"><div><div className="text-xs tracking-[.22em] uppercase opacity-50">Journal</div><h1 className="serif text-4xl mt-1">Your story</h1></div><button onClick={onAdd} className="h-12 w-12 rounded-2xl bg-[#8d7df0] text-white flex items-center justify-center"><Plus/></button></div><div className="soft rounded-3xl p-5 mb-5"><div className="flex items-center justify-between"><button><ChevronLeft size={18}/></button><div className="text-sm font-medium">September 2026</div><button><ChevronRight size={18}/></button></div><div className="grid grid-cols-7 gap-2 mt-5 text-center text-xs">{["M","T","W","T","F","S","S"].map(d=><span key={d} className="opacity-45">{d}</span>)}{Array.from({length:30},(_,i)=>i+1).map(d=><button key={d} onClick={()=>{const e=entries.find(x=>x.date.includes(String(d)))||entries[0];setSelected(e)}} className={d===18?"h-8 w-8 rounded-full bg-[#8d7df0] text-white":"h-8 w-8 mx-auto rounded-full hover:bg-white/70"}>{d}</button>)}</div></div><div className="space-y-3">{entries.map(e=><button onClick={()=>setSelected(e)} key={e.id} className="soft rounded-3xl p-5 w-full text-left"><div className="text-xs opacity-50">{e.date} · {e.mood}</div><div className="text-xl font-semibold mt-2">{e.title||"Untitled entry"}</div><div className="text-sm opacity-70 mt-2 line-clamp-3">{e.body||"Empty entry"}</div></button>)}</div></main>}
function JournalEditor({entry,onBack,onSave}:{entry:Entry;onBack:()=>void;onSave:(e:Entry)=>void}){const[local,setLocal]=useState(entry);return <main><div className="flex items-center justify-between mb-4"><button onClick={onBack}><ChevronLeft/></button><button onClick={()=>onSave(local)} className="px-4 py-2 rounded-2xl bg-[#28252d] text-white">Save</button></div><div className="text-xs uppercase tracking-[.2em] opacity-50 mb-4">{local.date}</div><div className="flex flex-wrap gap-2 mb-4">{["Calm","Reflective","Grateful","Energized","Challenging"].map(m=><button key={m} onClick={()=>setLocal({...local,mood:m})} className={`px-3 py-1.5 rounded-full text-sm border ${local.mood===m?"bg-[#8d7df0] text-white":"bg-white/60"}`}>{m}</button>)}</div><input value={local.title} onChange={e=>setLocal({...local,title:e.target.value})} placeholder="Title (optional)" className="w-full bg-transparent outline-none text-3xl mb-4"/><textarea autoFocus value={local.body} onChange={e=>setLocal({...local,body:e.target.value})} placeholder="What's on your mind?" className="w-full min-h-[58vh] bg-transparent outline-none resize-none leading-8 text-lg"/><div className="soft rounded-2xl p-3 mt-3 flex items-center gap-3 text-[#7568d7]"><Mic/><span className="text-sm">Voice note</span><div className="ml-auto text-xs opacity-50">{local.body.trim()?local.body.trim().split(/\s+/).length:0} words</div></div></main>}
function Tasks({tasks,setTasks,onAdd}:{tasks:Task[];setTasks:(t:Task[])=>void;onAdd:(title:string)=>void}){const[t,setT]=useState("");return <main><div className="flex items-end justify-between mb-5"><div><div className="text-xs tracking-[.22em] uppercase opacity-50">Tasks</div><h1 className="serif text-4xl mt-1">What needs doing?</h1></div></div><div className="grid gap-3">{tasks.map(t=><div key={t.id} className="soft rounded-3xl p-4 flex items-center gap-3"><button onClick={()=>setTasks(tasks.map(x=>x.id===t.id?{...x,done:!x.done}:x))} className={t.done?"h-6 w-6 rounded-full bg-[#8d7df0] text-white flex items-center justify-center":"h-6 w-6 rounded-full border-2 border-[#b7adbf]"}>{t.done&&<Check size={14}/>}</button><div className="flex-1"><div className={t.done?"line-through opacity-50":"font-medium"}>{t.title}</div></div><span className="text-xs px-2 py-1 rounded-full bg-white/70">{t.priority}</span><button onClick={()=>setTasks(tasks.filter(x=>x.id!==t.id))}><Trash2 size={16} className="opacity-50"/></button></div>)}</div><div className="soft rounded-2xl p-3 mt-4 flex gap-2"><input value={t} onChange={e=>setT(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){onAdd(t);setT("")}}} placeholder="New task..." className="flex-1 bg-transparent outline-none"/><button onClick={()=>{onAdd(t);setT("")}} className="h-10 w-10 rounded-xl bg-[#28252d] text-white flex items-center justify-center"><Plus size={17}/></button></div></main>}
function SearchView({query,setQuery,results}:{query:string;setQuery:(q:string)=>void;results:{kind:string;title:string;body:string;id:number}[]}){return <main><div className="text-xs tracking-[.22em] uppercase opacity-50">Search</div><h1 className="serif text-4xl mt-1 mb-4">Find anything</h1><div className="soft rounded-2xl px-4 py-3 flex items-center gap-2"><Search size={18}/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search notes, journal, tasks..." className="bg-transparent outline-none flex-1"/></div><div className="mt-5 grid gap-3">{query&&results.map(r=><div key={r.kind+r.id} className="soft rounded-2xl p-4"><div className="text-xs opacity-50">{r.kind}</div><div className="font-semibold mt-1">{r.title}</div><div className="text-sm opacity-60 mt-1">{r.body}</div></div>)}</div></main>}
function SettingsView({theme,setTheme}:{theme:keyof typeof themes;setTheme:(t:keyof typeof themes)=>void}){return <main><div className="text-xs tracking-[.22em] uppercase opacity-50">Settings</div><h1 className="serif text-4xl mt-1">Make it yours</h1><div className="soft rounded-3xl p-5 mt-6"><div className="flex items-center gap-3"><div className="h-11 w-11 rounded-full pastel-lavender flex items-center justify-center"><Sun size={19}/></div><div><div className="font-semibold">Appearance</div><div className="text-sm opacity-60">Choose the feeling of Morrow</div></div></div><div className="grid grid-cols-2 gap-3 mt-5">{Object.entries(themes).map(([name,c])=><button key={name} onClick={()=>setTheme(name as keyof typeof themes)} className={`rounded-2xl p-4 text-left border-2 ${theme===name?"border-[#7c6be3]":"border-transparent"}`} style={{background:c.bg}}><div className="flex gap-1 mb-3">{[0,1,2].map(i=><span key={i} className="h-3 w-3 rounded-full" style={{background:c.accent,opacity:1-i*.18}}/>)} </div><div className="font-medium">{name}</div></button>)}</div></div><div className="soft rounded-3xl p-5 mt-4"><div className="font-semibold">Account</div><div className="text-sm opacity-60 mt-1">Continue with Google</div><button className="mt-4 w-full rounded-2xl bg-white px-4 py-3 border flex items-center justify-center gap-2"><span className="font-semibold">G</span> Continue with Google</button></div><div className="soft rounded-3xl p-5 mt-4"><div className="font-semibold">Data</div><div className="text-sm opacity-60 mt-1">Your Morrow data will be stored with your connected backend.</div><button className="mt-4 px-4 py-2 rounded-2xl border">Export</button></div></main>}
function QuickCapture({onClose,onSave}:{value:string;onClose:()=>void;onSave:(v:string)=>void}){const[v,setV]=useState("");return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/25 backdrop-blur-sm"><div className="w-full max-w-[720px] rounded-t-[32px] bg-[#fbf8fc] p-6 pb-8 shadow-2xl"><div className="flex items-center justify-between"><div className="serif text-3xl">Quick capture</div><button onClick={onClose}><X/></button></div><div className="text-sm opacity-60 mt-2">Dump anything. Morrow keeps it safe.</div><textarea autoFocus value={v} onChange={e=>setV(e.target.value)} placeholder="Buy microphone\nIdea for video\nNeed to research Japan\nFeeling stuck today..." className="mt-5 w-full h-44 rounded-3xl bg-white border border-[#eadfea] p-5 outline-none resize-none leading-7"/><div className="flex gap-3 mt-4"><button className="h-12 w-12 rounded-2xl bg-white border flex items-center justify-center"><Mic/></button><button onClick={()=>onSave(v)} className="flex-1 rounded-2xl bg-[#29252f] text-white font-medium">Save to inbox</button></div></div></div>}
function Nav({tab,setTab,onAdd}:{tab:Tab;setTab:(t:Tab)=>void;onAdd:()=>void}){return <div className="fixed bottom-0 left-0 right-0 z-40"><div className="max-w-[720px] mx-auto px-4 pb-4"><div className="soft rounded-[26px] px-3 py-2 flex items-center justify-between"><NavBtn icon={<Home size={19}/>} label="Home" active={tab==="home"} onClick={()=>setTab("home")}/><NavBtn icon={<FileText size={19}/>} label="Notes" active={tab==="notes"} onClick={()=>setTab("notes")}/><button onClick={onAdd} className="h-12 w-12 rounded-2xl bg-[#8d7df0] text-white flex items-center justify-center shadow-lg"><Plus/></button><NavBtn icon={<BookOpen size={19}/>} label="Journal" active={tab==="journal"} onClick={()=>setTab("journal")}/><NavBtn icon={<CheckCircle2 size={19}/>} label="Tasks" active={tab==="tasks"} onClick={()=>setTab("tasks")}/><NavBtn icon={<Search size={19}/>} label="Search" active={tab==="search"} onClick={()=>setTab("search")}/></div></div></div>}
function NavBtn({icon,label,active,onClick}:{icon:React.ReactNode;label:string;active:boolean;onClick:()=>void}){return <button onClick={onClick} className={`flex flex-col items-center gap-1 px-2 py-1 rounded-xl ${active?"text-[#6f61d3]":"text-[#6d6570]"}`}>{icon}<span className="text-[10px]">{label}</span></button>}
export default App;